# referd https://github.com/fastai/nbdev_template/blob/master/docker-compose.yml
version: "3"
services:
  jupyter:
    restart: unless-stopped
    image: lilacs2039/fastai-nbdev
    container_name: nbdev-jupyter
    # run nbdev_build, jupyter
    command: >
      bash -c "nbdev_build_lib && nbdev_build_docs
      && pip install -e .
      && export SHELL=/bin/bash && source ~/.bashrc
      && jupyter lab --allow-root --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --NotebookApp.password=''"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace/
    ports:
      - "8888:8888"

  jekyll:
    image: fastai/jekyll
    container_name: nbdev-jekyll
    depends_on:
      - jupyter
    command: >
     bash -c "cd docs
     && bundle i
     && chmod -R u+rwx . 
     && bundle exec jekyll serve --host 0.0.0.0 --trace"
    working_dir: /workspace
    volumes:
      - .:/workspace/
    ports:
     - "4000:4000"

